Snips.addText("de", :which_lamp, "Ich habe nicht verstanden welche Lampe ich schalten soll")
Snips.addText("de", :what_to_do, "Ich habe nicht verstanden was ich mit dem Licht machen soll")
Snips.addText("de", :no_matched_light, "Ich finde kein passendes Licht!")
Snips.addText("de", :ok, "OK")
Snips.addText("de", :ok, "bitte")
Snips.addText("de", :ok, "bitte sehr")
Snips.addText("de", :ok, "ja")
Snips.addText("de", :ok, "mach ich")
Snips.addText("de", :ok, "wird gemacht")
Snips.addText("de", :script_error, "Das Skript zur Steuerung der Shellybulb konnte nicht ausgeführt werden!")
Snips.addText("de", :error_gpio_cmd, "Über GPIO kann das Licht nur ein- und ausgeschaltet werden!")

Snips.addText("en", :which_lamp, "I could not detect which light to switch!")
Snips.addText("en", :what_to_do, "I could not detect what to do with the light!")
Snips.addText("en", :no_matched_light, "No matched light found!")
Snips.addText("en", :ok, "OK")
Snips.addText("en", :script_error, "Error executing the control script for Shellybulb!")
Snips.addText("en", :error_gpio_cmd, "GPIO controlled light only can be switched on or off!")
)
